apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekEwTVRVeApOak15TkRCYUZ3MDBNekEwTVRVeE5qTXlOREJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEbzVlS0pqYkZHZTFlL1dKeFVLcGRxclNOSUc5ZlhBZ01CdjFycEZhb2JOY0pjME5hZwpHWVROOCtpNjlRWldVQys2TStubmdQNk8xaFptZDZyREVDZ1VuT1RTNDd6TldRU3FSWlYxQkZjelJZNWdScHR1CkliN2JiYml3SThNWkNXblhyZTFwenZ6bEpDU1NzdkU2ZXVUa0NnOEE5T0tHYmJ4aFpzRzJxSndNM1ZFSms3SzcKS2ljYm5QcElIZEJZdklPMm1EQklpalppZmsrNTZNekRRNExlV2R1UkowSUJUUFdxMDhYRWpJQ3NEeERaaW1CawpEQUdmQTZPYVJrYWtUTjBzS2tqSk5Dc210YTlPbTJqN1Zrb3dsU0Y1OElIb1pjRzk1cjlJbXZRbWQwL01waGpxCkh5YU42MWtVQnZISi9yd0JyVFRYL2xwakJrVjhYT3VrN1h2VEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlJicUpLbGE4a1FEWUZxeEdRNQpCWWJFc0I2Yit6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFqZWRQYW04aG5TdXpmNVZ2Q25ZZXp5Qk5CTUxmCkp4QzNxdlhSK2E3Ymxvb2ovR1EyTUZmUk5ydkMxSEd5ZW1ucC9Udk9Pd1FjeDFtSTIydjlmVXRacmlwWmpydkoKcE00OGRGOUw0NDY3N2s5bHNoS2lib2s2cUQ5R2tDYUlzb1lsR2RlcEVpa3NBdzhUUzFEdGlqNVJCbVMzcWtHQQpZdVgrZXFYN2Qrc2xrZDZUZVBKemYzUU5Ga3NPUG1UQUVBUVpXL0JidnpEc0FpcTRmNFk5MElubkpISHpaVzliCm5jdnBxVW5mYzJWS0dVTTFiRXlGNlZLWUpQNkt2VTZsS1gyUmZCTVluWmhYSFp5bDZ6WXAwZFJxeVdWd0plZGkKWVd2djFZTzV1azkzSUpRcXBXQ3dlM0I2d2ZvM0JBRm85aS80dWlOa202WGhVSGI0dEYwWWxoSmgzZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://ee83c4bf-2643-40a2-b315-efef4563b608.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_d296f13b4e74973678ea5488372aeaa9ef95cca4948ee32fa57b5475604b36b6
